# Generated by Django 5.2.3 on 2025-06-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], max_length=7, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('MORADIA', 'Moradia'), ('TRANSPORTE', 'Transporte'), ('ALIMENTACAO', 'Alimentação'), ('SAUDE', 'Saúde'), ('LAZER', 'Lazer'), ('EDUCACAO', 'Educação'), ('PESSOAIS', 'Despesas Pessoais'), ('OUTRAS_DESPESAS', 'Outras Despesas'), ('SALARIO', 'Salário / Pró-labore'), ('INVESTIMENTOS', 'Rendimentos'), ('OUTRAS_RECEITAS', 'Outras Receitas')], max_length=20, verbose_name='Categoria')),
                ('date', models.DateField(verbose_name='Data da Transação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
