# Generated by Django 5.2.3 on 2025-06-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personaltransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='law_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.lawcase', verbose_name='Processo'),
        ),
    ]
